-- Verificar URI del contrato en la base de datos
SELECT 
    CONTRACT_UID,
    SIGNED_PDF_URI,
    SIGNED_PDF_SHA256,
    PDF_STORAGE_TYPE,
    PDF_GENERATED_AT
FROM IC_ADMIN.CONTRACTS 
WHERE CONTRACT_UID LIKE 'CBRO-I-TEST%'
ORDER BY CREATED_AT DESC;
