-- Verificar contratos duplicados
SELECT CONTRACT_UID, COUNT(*) as TOTAL
FROM IC_ADMIN.CONTRACTS 
WHERE CONTRACT_UID = 'CBRO-I-12346'
GROUP BY CONTRACT_UID;

-- Ver todos los contratos
SELECT ID, CONTRACT_UID, STATUS, CREATED_AT
FROM IC_ADMIN.CONTRACTS 
ORDER BY CREATED_AT DESC;

-- Ver partes de contratos
SELECT CONTRACT_ID, PARTY_TYPE, FULL_NAME
FROM IC_ADMIN.CONTRACT_PARTIES
WHERE CONTRACT_ID IN (
    SELECT ID FROM IC_ADMIN.CONTRACTS WHERE CONTRACT_UID = 'CBRO-I-12346'
);
