-- =====================================================
-- ACTUALIZACIÓN SIMPLE DEL ESQUEMA PARA OBJECT STORAGE
-- =====================================================
-- Este script solo incluye las modificaciones básicas que ic_user puede ejecutar

-- 1. Agregar columnas para Object Storage
ALTER TABLE IC_ADMIN.CONTRACTS ADD (
    SIGNED_PDF_URI        VARCHAR2(500),  -- URL del PDF en Object Storage
    SIGNED_PDF_SHA256     VARCHAR2(64),   -- Hash SHA256 para integridad
    PDF_STORAGE_TYPE      VARCHAR2(20)    -- 'MINIO', 'S3', 'ORACLE_OBJECT_STORAGE'
);

-- 2. Agregar comentarios para documentación
COMMENT ON COLUMN IC_ADMIN.CONTRACTS.SIGNED_PDF_URI IS 'URI del PDF firmado en Object Storage (MinIO/S3/Oracle)';
COMMENT ON COLUMN IC_ADMIN.CONTRACTS.SIGNED_PDF_SHA256 IS 'Hash SHA256 del PDF para verificar integridad';
COMMENT ON COLUMN IC_ADMIN.CONTRACTS.PDF_STORAGE_TYPE IS 'Tipo de Object Storage usado: MINIO, S3, ORACLE_OBJECT_STORAGE';

-- 3. Crear tabla para auditoría de Object Storage (solo si tienes permisos)
CREATE TABLE IC_ADMIN.OBJECT_STORAGE_AUDIT (
    ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    CONTRACT_ID     NUMBER(19) NOT NULL,
    OPERATION       VARCHAR2(20) NOT NULL,  -- 'UPLOAD', 'DOWNLOAD', 'DELETE'
    STORAGE_TYPE    VARCHAR2(20) NOT NULL,  -- 'MINIO', 'S3', 'ORACLE_OBJECT_STORAGE'
    OBJECT_URI      VARCHAR2(500) NOT NULL,
    FILE_SIZE       NUMBER(19),
    SHA256_HASH     VARCHAR2(64),
    OPERATED_BY     VARCHAR2(100),
    OPERATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    SUCCESS         CHAR(1) DEFAULT 'Y' CHECK (SUCCESS IN ('Y', 'N')),
    ERROR_MESSAGE   VARCHAR2(1000)
);

-- 4. Crear índices para performance
CREATE INDEX IDX_CONTRACTS_PDF_URI ON IC_ADMIN.CONTRACTS(SIGNED_PDF_URI);
CREATE INDEX IDX_CONTRACTS_STORAGE_TYPE ON IC_ADMIN.CONTRACTS(PDF_STORAGE_TYPE);
CREATE INDEX IDX_OBJ_AUDIT_CONTRACT ON IC_ADMIN.OBJECT_STORAGE_AUDIT(CONTRACT_ID);
CREATE INDEX IDX_OBJ_AUDIT_OPERATION ON IC_ADMIN.OBJECT_STORAGE_AUDIT(OPERATION, OPERATED_AT);

-- 5. Insertar datos de configuración en IC_LOV
INSERT INTO IC_ADMIN.IC_LOV (LOV_KEY, LOV_DESCRIPTION, CREATION_DATE, CREATION_USER, UPDATE_DATE, UPDATE_USER) 
VALUES ('OBJECT_STORAGE_TYPE', 'Tipo de Object Storage por defecto', SYSDATE, USER, SYSDATE, USER);

INSERT INTO IC_ADMIN.IC_LOV (LOV_KEY, LOV_DESCRIPTION, CREATION_DATE, CREATION_USER, UPDATE_DATE, UPDATE_USER) 
VALUES ('MINIO_ENDPOINT', 'Endpoint de MinIO', SYSDATE, USER, SYSDATE, USER);

INSERT INTO IC_ADMIN.IC_LOV (LOV_KEY, LOV_DESCRIPTION, CREATION_DATE, CREATION_USER, UPDATE_DATE, UPDATE_USER) 
VALUES ('MINIO_BUCKET', 'Bucket por defecto para PDFs', SYSDATE, USER, SYSDATE, USER);

COMMIT;

-- 6. Verificar la instalación
SELECT 'SCHEMA_UPDATE_COMPLETED' AS STATUS FROM DUAL;

-- Mostrar información de la configuración
SELECT 
    'CONTRACTS_TABLE_UPDATED' AS STATUS,
    COUNT(*) AS TOTAL_CONTRACTS
FROM IC_ADMIN.CONTRACTS;

SELECT 
    'OBJECT_STORAGE_CONFIG' AS CONFIG_TYPE,
    LOV_KEY,
    LOV_DESCRIPTION
FROM IC_ADMIN.IC_LOV 
WHERE LOV_KEY IN ('OBJECT_STORAGE_TYPE', 'MINIO_ENDPOINT', 'MINIO_BUCKET');
